# Generated by Django 5.0.4 on 2024-04-26 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/photo/', verbose_name='photo')),
                ('followercount', models.IntegerField(default=0, verbose_name='followercount')),
                ('access', models.CharField(blank=True, max_length=1000, null=True, verbose_name='access')),
                ('refresh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='refresh')),
                ('is_login', models.BooleanField(default=False, verbose_name='is_login')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='uinfos', to='CustomUser.cuser', to_field='username', verbose_name='username')),
            ],
            options={
                'verbose_name': 'uinfo',
                'verbose_name_plural': 'uinfos',
            },
        ),
    ]
