# Generated by Django 5.0.4 on 2024-04-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_remove_uinfo_access_remove_uinfo_is_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uinfo',
            old_name='followercount',
            new_name='followerCount',
        ),
    ]
