# Generated by Django 5.0.4 on 2024-04-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('followed', models.ForeignKey(db_column='followed', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='CustomUser.cuser', to_field='username', verbose_name='followed')),
                ('follower', models.ForeignKey(db_column='follower', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='CustomUser.cuser', to_field='username', verbose_name='follower')),
            ],
            options={
                'verbose_name': 'relation',
                'verbose_name_plural': 'relations',
            },
        ),
    ]
