# Generated by Django 5.0.4 on 2024-04-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRelation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
