# Generated by Django 5.0.4 on 2024-04-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImgSrc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imginfo',
            options={'verbose_name': 'imginfo', 'verbose_name_plural': 'imginfos'},
        ),
    ]
